<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="com.manish.dao.MovieDAO, com.manish.beans.MovieBean" %>
<%
    String movieIdStr = request.getParameter("movieId");
    if (movieIdStr == null || movieIdStr.isEmpty()) {
        response.sendRedirect("movies.jsp");
        return;
    }
    
    int movieId = Integer.parseInt(movieIdStr);
    MovieDAO movieDao = new MovieDAO();
    MovieBean movie = movieDao.getMovieById(movieId);
    
    if (movie == null) {
        response.sendRedirect("movies.jsp");
        return;
    }
%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Book Tickets - <%= movie.getTitle() %></title>
    <link rel="stylesheet" href="css/style.css">
    <style>
        .seat-map {
            display: grid;
            grid-template-columns: repeat(10, 1fr);
            gap: 10px;
            margin: 20px 0;
        }
        .seat {
            width: 30px;
            height: 30px;
            background-color: #ddd;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            border-radius: 4px;
        }
        .seat.selected {
            background-color: #4CAF50;
            color: white;
        }
        .seat.occupied {
            background-color: #f44336;
            cursor: not-allowed;
        }
        .screen {
            background: #333;
            color: white;
            text-align: center;
            padding: 10px;
            margin: 20px 0;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <jsp:include page="header.jsp"/>
    
    <main class="container">
        <h2>Book Tickets for <%= movie.getTitle() %></h2>
        
        <form action="processBooking.jsp" method="POST">
            <input type="hidden" name="movieId" value="<%= movie.getMovieId() %>">
            
            <div class="form-group">
                <label for="showDate">Show Date:</label>
                <input type="date" id="showDate" name="showDate" required 
                       min="<%= new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) %>">
            </div>
            
            <div class="form-group">
                <label for="showTime">Show Time:</label>
                <select id="showTime" name="showTime" required>
                    <option value="">Select Time</option>
                    <option value="10:00 AM">10:00 AM</option>
                    <option value="1:00 PM">1:00 PM</option>
                    <option value="4:00 PM">4:00 PM</option>
                    <option value="7:00 PM">7:00 PM</option>
                    <option value="10:00 PM">10:00 PM</option>
                </select>
            </div>
            
            <div class="screen">SCREEN</div>
            
            <div class="form-group">
                <label>Select Seats:</label>
                <div class="seat-map" id="seatMap">
                    <!-- Seats will be generated by JavaScript -->
                </div>
                <input type="hidden" id="seats" name="seats" required>
            </div>
            
            <div class="form-group">
                <label>Total Price:</label>
                <span id="totalPrice">$0.00</span>
                <input type="hidden" id="totalPriceValue" name="totalPrice" value="0">
            </div>
            
            <button type="submit" class="btn">Proceed to Payment</button>
        </form>
    </main>
    
    <jsp:include page="footer.jsp"/>
    
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const seatMap = document.getElementById('seatMap');
            const seatsInput = document.getElementById('seats');
            const totalPriceSpan = document.getElementById('totalPrice');
            const totalPriceValue = document.getElementById('totalPriceValue');
            const pricePerSeat = <%= movie.getPrice() %>;
            
            // Generate seats (A1-J10)
            for (let row = 0; row < 10; row++) {
                for (let col = 1; col <= 10; col++) {
                    const seat = document.createElement('div');
                    seat.className = 'seat';
                    seat.textContent = String.fromCharCode(65 + row) + col;
                    
                    // Randomly mark some seats as occupied for demo
                    if (Math.random() < 0.2) {
                        seat.classList.add('occupied');
                    } else {
                        seat.addEventListener('click', function() {
                            this.classList.toggle('selected');
                            updateSelectedSeats();
                        });
                    }
                    
                    seatMap.appendChild(seat);
                }
            }
            
            function updateSelectedSeats() {
                const selectedSeats = document.querySelectorAll('.seat.selected');
                const seatNumbers = Array.from(selectedSeats).map(seat => seat.textContent);
                seatsInput.value = seatNumbers.join(',');
                
                // Calculate total price
                const total = selectedSeats.length * pricePerSeat;
                totalPriceSpan.textContent = '$' + total.toFixed(2);
                totalPriceValue.value = total;
            }
        });
    </script>
</body>
</html>