package com.manish.bean;
// Generated 20 Mar, 2025 8:39:00 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int sid;
     private String name;
     private String enroll;
     private Integer p;
     private Integer c;
     private Integer m;
     private Integer h;
     private Integer e;
     private Integer total;
     private Float per;

    public Student() {
    }

	
    public Student(int sid) {
        this.sid = sid;
    }
    public Student(int sid, String name, String enroll, Integer p, Integer c, Integer m, Integer h, Integer e, Integer total, Float per) {
       this.sid = sid;
       this.name = name;
       this.enroll = enroll;
       this.p = p;
       this.c = c;
       this.m = m;
       this.h = h;
       this.e = e;
       this.total = total;
       this.per = per;
    }
   
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEnroll() {
        return this.enroll;
    }
    
    public void setEnroll(String enroll) {
        this.enroll = enroll;
    }
    public Integer getP() {
        return this.p;
    }
    
    public void setP(Integer p) {
        this.p = p;
    }
    public Integer getC() {
        return this.c;
    }
    
    public void setC(Integer c) {
        this.c = c;
    }
    public Integer getM() {
        return this.m;
    }
    
    public void setM(Integer m) {
        this.m = m;
    }
    public Integer getH() {
        return this.h;
    }
    
    public void setH(Integer h) {
        this.h = h;
    }
    public Integer getE() {
        return this.e;
    }
    
    public void setE(Integer e) {
        this.e = e;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public Float getPer() {
        return this.per;
    }
    
    public void setPer(Float per) {
        this.per = per;
    }




}


